engines:
    duplication:
        enabled: true
        config:
            languages:
                - javascript
    fixme:
        enabled: true
    markdownlint:
        enabled: true
    stylelint:
        enabled: true
        channel: "beta"
ratings:
    paths:
        - "**.js"
        - "**.md"
        - "**.css"
