engines:
    duplication:
        enabled: true
        config:
            languages:
                - javascript
    fixme:
        enabled: true
    markdownlint:
        enabled: true
ratings:
    paths:
        - "**.js"
        - "**.md"
        - "**.css"
